PATHS:
  TRAIN: "~CONFIG/../Data/train/"
  VALIDATION: "~CONFIG/../Data/val/"
  TEST1: "~CONFIG/../Data/boulders/"
  TEST2: "~CONFIG/../Data/no_boulders/"

MODE: "train_vae"
CUDA: "0"

DATA:
  SHELL_SIZE: 3
  VOXEL_SIZE: 0.2
  IN_SIZE: 48

AUG:
  ROTATE: False
  FLIP: True

VAE_MODEL:
  HAS_PARAMS: True
  TYPE: "unet"
  F_START: 16

TRAIN:
  IT_P_EP: 1000
  N_EP_MAX: 100
  EARLY_STOPPING_EP: 10
  BTSZ: 16
  NUM_WK: 4
  PREFETCH_FACTOR: 16
  LOSS:
    TYPE: "dice"
  VAE:
    OPTIM: "adam"
    LR: 0.0001
    BETA1: 0.0
    BETA2: 0.999
    WDEC: 0.0
TEST:
  NUM_POINTS: 2500

CHECKPOINTS:
  LOAD_FROM: ""
  SAVE: True
  LOAD: True
  LOAD_OPT: True

OUTPUTS:
  SAVE_TRAIN: True
  SAVE_METRICS: True
  FOLDER: "~CONFIG/results/vae_48_f16"

VERSION: 1.17
